### ISSUE TITLE
Postgres follows standards for operator `||`

### ISSUE THREAD

**Issue by kumy** [ikkez/f3-cortex#98] opened 2020-04-01 17:32 UTC
While we tried to find a solution for #97, I've found that `cortex` assume that all db engines interpret the `||` as `OR` function.

https://github.com/ikkez/f3-cortex/blob/364caaa15132824a26ee0207e35b70750c50e5ae/lib/db/cortex.php#L2585

As per the Postgres wiki, Mysql "violates database standards".

> MySQL uses C-language operators for logic (i.e. 'foo' || 'bar' means 'foo' OR 'bar', 'foo' && 'bar' means 'foo' and 'bar'). This might be marginally helpful for C programmers, but violates database standards and rules in a significant way. PostgreSQL, following the standard, uses || for string concatenation ('foo' || 'bar' = 'foobar'). 
https://wiki.postgresql.org/wiki/Things_to_find_out_about_when_moving_from_MySQL_to_PostgreSQL

**Mysql**
![Screenshot from 2020-04-01 19-29-16](https://user-images.githubusercontent.com/176794/78167722-3219a000-744f-11ea-98cf-58ed3a92d788.png)

**Postgres**
![Screenshot from 2020-04-01 19-29-33](https://user-images.githubusercontent.com/176794/78167710-2c23bf00-744f-11ea-814c-289057532776.png)

This substitution should be dependent on the underlying db engine at least for Postgres.

**Comment by ikkez** [comment] 2020-04-01 17:54
Oh well.. could it be worse? 
I've checked sqlite and sql server and they do not use || for or, but also for concatination. The code is there to unify some behaviours and expectations for queries. How would have thought that that statements means concat? Me not, as I wrote that. The problem is when i remove that now, it would break compatibility, since i do not know if that was something intentionally used in any project.. and since the "normal" syntax for Jig, or MySQL would recognize it as OR, I'm not sure what would be the option here. Maybe make that array configurable as workaround?!

**Comment by kumy** [comment] 2020-04-01 18:02
> it would break compatibility, since i do not know if that was something intentionally used in any project

I understand, such change should be taken with care. Should choose between making it a deprecation and fix it for engines we know use it as `CONCAT()` vs adding an option to enable "`standards`"…

**Comment by ikkez** [comment] 2020-04-01 23:01
Should be fixed now. I'll remove it in a future version.

**Closed** 2020-06-18 16:08 UTC
Labels: enhancement
