### ISSUE TITLE
One-Many models relationship

### ISSUE THREAD

**Issue by royhg** [ikkez/f3-cortex#32] opened 2016-10-03 09:26 UTC
Hallo Ikkez,

Can I used this class for relational load, CRUD without creating schema?
If so, can someone inspiring me how to setup master/detail?

Tq.
Roy

**Comment by ikkez** [comment] 2016-10-04 08:39
Can you give more details about what you want to achieve? For me it looks like you want a) a model with one-to-many relations or a simple field to store JSON with your *detail_data*.

**Comment by royhg** [comment] 2016-10-05 05:23
Hello Ikkez,

Thanks for your reply, It's already progress to try out now..
It was default that id field name become _id in the mapper records?
Can I achive the default id field not changed? and still could related with another field in another table as a relation?
tq.
Roy.

example:
Tenant:                        Bill:
id   belongs-to-one    tenantId
                                   tenant has-many,id(Tenant)

When I load tenant it seems that the primary(id) has become _id automatically, 
How can the id field still acknowledge by template?

tq.

**Comment by ikkez** [comment] 2016-10-05 09:59
The field `id` is still there (at least when you use a SQL db). You should be able to access this with `$mapper->id` nevertheless.
It's mapped to `_id` to unify it with the other F3 mappers. You can disabled that by setting `$f3->set('CORTEX.standardiseID',false);`

For relation examples see 
https://github.com/ikkez/f3-cortex#relations
and
https://github.com/ikkez/fabulog/tree/master/app/model

**Comment by royhg** [comment] 2016-10-19 02:33
Hi Christian,

How do we set in model for multiple primary key?
ex:
class payment1 extends cortexModel {
protected
$primary='id.row' =>if (myPK is id,row)
}

I saw your code there is var $saveCsd(boolean) to save Cascade mode on relationship?
How do we set value of relation fields in the master Table when there is new not updated?
Coz I have error same like after this issue..
eg:
Payment model
id(PK),date,payment1(relation field contain payment1 collection)
Payment1 model
id(PK),row(PK),value,subtotal

How do we set and save payment1 field at payment model?

tq.

**Comment by ikkez** [comment] 2016-10-19 09:02
well, saving a relation goes like this:

```php
$payment = new \models\Payment();
//some codes for $payment
$payment1 = new \models\Payment1();
//some codes for $payment1
$payment1->save();
$payment->payment1 = $payment1 ; 
$payment->save();
```
But I am afraid that there is no magic included for handling multiple primary keys automatically when binding relations. In that case you need two fields in Payment model (for payment1.id and payment1.row), you have to bind both and do the loading of them yourself too. Sorry for that. 
What's wrong about having payment1.id as an autoincremented primary key and payment1.row as a simple index? That way you can simply bind the models with the code above and have no problems loading them accross parent models.

**Comment by royhg** [comment] 2016-10-26 08:18
Hi Christian,
How we can configure deep relation of table?

t1->t2->t3,

t1.fieldconf=[
'id'=>['has-many'=>['t2','id]]
],

t2.fieldconf=[
'id'=>['belongs-to-one'=>['t1','id]],
'ft2'=>['has-many'=>['t3','id]],
]

t3.fieldconf=[
'id'=>['belongs-to-one'=>['ft2','id]],
]

is it true the configuration like above?

tq.

**Comment by ikkez** [comment] 2016-10-26 09:29
try this

```php
m1.fieldconf=[
'v2'=>['has-many'=>['m2','f1']] // v2 has many m2, where f1 matches my primary (m1.id) 
],

m2.fieldconf=[
'f1'=>['belongs-to-one'=>['m1','id']], // value in f1 belongs to one m1.id
'v3'=>['has-many'=>['m3','f2']],       // v3 has many m3, where m3.f2 == m2.id
]

m3.fieldconf=[
'f2'=>['belongs-to-one'=>['m2','id']], // value in f2 belongs to one m2.id
]

m = Model Namespace
v* = virtual field name (not existing in DB table)
f* = field name (is existing in table)
```
should create a tree like this:
```
m1.v2=>[
  m2.v3=>[
      m3,
      m3,
      m3,
  ],
  m2.v3=>[
      m3,
      m3,
      m3,
  ],
  m2.v3=>[
      m3,
      m3,
      m3,
  ],
]

**Comment by royhg** [comment] 2016-10-27 02:21
Hi Christian,

Tq for reply,
But It lightly different a bit,

m2.fieldconf=[
'f1'=>['belongs-to-one'=>['m1','id']], // value in f1 belongs to one m1.id
'v3'=>['has-many'=>['m3','f2']],       // v3 has many m3, where m3.f2 == "m2.f3"  not "m2.id" ?

I already update the m3 model 
m3.fieldconf=[
'f2'=>['belongs-to-one'=>['m2','f3']], // value in m3.f2 belongs to one m2.f3 not m2.id?
but still no luck.

Is It possible?
tq.

**Comment by ikkez** [comment] 2016-11-14 22:27
hey roy, sorry for the delay... I lost track of it. Were you able to solve it already? maybe you just need to flip the m2.v3 and m3.f2 definitions? It's hard to tell from here. I'll have a look into building a little UI tool for easier relation setup maybe?! kind regards.

**Comment by stvowi** [comment] 2016-11-14 22:37
UI tool would be great!

**Comment by royhg** [comment] 2016-11-15 04:18
Hey, Christian,

Basically your cortex tools is already great!
But if allowed I want to say some of condition I found,
1. When I created a new relation field to another table, 
is it true that current table field related become null and have child array of relation table?
Why you can permitted current field value still have their value and make child array of related table without current field related value?
2. On Cortex config, it seems that field without primary key can not have foreign key, actually some of needs config is. I think is faster modify cortex to fulfill commons basic of relation table database than creating a new UI relation setup. It just a little modif my friend. your tools is already did that.
3. I just wondered that cortex have auto delete and insert for detail foreign key for current related field,
as example as I tested cortex, I can auto updated foreign key detail field after primary records has been exists in the database, but for the first inserted, I need to manual inserted to the foreign related table, actually basic cursor of f3 after cortex has been setup is already related. what I mean is the basic of f3 cursor to copyTo and copyFrom method to array is great, but it is failed when head to multidimensional array, It is become better if the method can be applied for multidimensional and cortex foreign key relationial field inserted, updated and deleted. So we just inserted/updated/deleted the value of current array and then when we copyTo and copyFrom to database the records are always aligned.
4. When I used foreign key setup on relational field, when I load the primary key records, If the foreign key records doesnt existed the cortex will raised any warning said that error Unknown column 'Array' in 'field list' was made. I still have no solution to clear that warn, even better if cortex have options to hide or to show the warn something like that so the error/warn become cleaner, 

Thanks for your great tools,
It was my honor to make a little contribution..

tq.
Roy.

**Comment by ikkez** [comment] 2017-03-01 12:42
hey @royhg, some thoughts while I'm currently getting my hands on this:
1. That sounds like an old bug to me. Usually the `belongs-to-one` fields are existing on the table and will contain a single relation object, while the `has-*` fields are not, but will contain an array of related objects.

2. You cannot use tables that do not have a primary key, because the F3 mapper has no way to determine that unique record in terms of updating it. However - the primary key actually is used as a foreign keys for all `belongs-to-one` configurations by default.

3. Yes that's a good idea and I'll have a look at implementing this.

4. Well if a related record was not found, it should skip the loading silently. If you try to update that non existing related mapper, it'll fail of course. I think Cortex should not try to create mappers on the fly where they arent used to be,.. there are some shortcuts to do so, but what is empty (or `NULL`) should stay in that state for better interoperability. But maybe there are some ways to improve the whole common set/get tasks.

thanks for your thoughts.

**Comment by royhg** [comment] 2017-03-21 08:17
Hi Christian,
I just asking in the same fields for a while..
If I already have cursor with multiple one many relational tables,
Did Cortex have a feature to save current cursor and multiple relational tables without configuring additional collections?
like below:
table:post
[id]=>'###',
[title]=>'xxx',
[author]=>[ 
     [0]=>[  ['id']=>'a1',['name']=>'xxx1' ],
     [1]=>[  ['id']=>'a2',['name']=>'xxx2' ]
],
[pubs]=>[ 
     [0]=>[  ['id']=>'p1',['name']=>'xxx1' ],
     [1]=>[  ['id']=>'p2',['name']=>'xxx2' ]
]
Can I run $post->save() for new records and author&pubs table auto save each without defining collections? but I already defined fieldConf in my model and each of the relations?

Regards,
Roy

**Comment by royhg** [comment] 2017-04-01 12:33
Hi Christian,
Why each time I check after copyFrom(array) the primaryKey of relation foreignkey is always empty?
Ex:
table1.fieldConf=[
  'table2'=>['has-many'=>['mTable2','id']]
];
table2.fieldConf=[
  'id'=>['belongs-to-one'=>['mTable1','table2']]
]

mTable2->erase($id);
foreach($arrTable2 as $item){
mTable2-reset();
mTable2->copyFrom($item);
mTable2->id='001' <- I already tried to set mTable2->id but it seems not updated
echo mTable2->cast(); <- each time I check the mTable2->id is always empty..
mTable2->save();
}

How can I set mTable2->id? 
bcause I always get error to save the Table2 data. 

Regards,
Roy

**Comment by ikkez** [comment] 2017-04-01 18:56
I think the config is screwed up. Try this instead:

```php
table1.fieldConf=[
  'table2'=>['belongs-to-one'=>['mTable2','id']]
];
table2.fieldConf=[
  'table1'=>['has-many'=>['mTable1','table2']]
]
```

**Comment by ikkez** [comment] 2018-04-17 10:00
Hi.. no #58 is about optimizing the strategy to find those records. And #61 is probably caused by a configuration issue, but you have not posted any details yet.
Anyways, I'm going to close this issue now, because it became a Q&A thread rather than a discussion about a specific issue. Please reopen another issue, if there's more :)

**Closed by ikkez** 2018-04-17 10:00 UTC
Labels: enhancement
