### ISSUE TITLE
Extra Data in a Has-Many- Has Many Relationship

### ISSUE THREAD

**Issue by acemureithi** [ikkez/f3-cortex#19] opened 2016-03-05 10:19 UTC
Hi,
I have Two models: Quotation and Product. 
Many Quotations can have the same Product and Many Products can be in the same quotation
````php
class Quotation extends \BaseModel {
    protected $table ="quotations";
    protected $fieldConf = array(
        'products' => array(
            'has-many' => array('\Models\Product','quotations','quotations_products')
        ),
        )
}
class Product extends \BaseModel {
    protected $table ="products";
    protected $fieldConf = array(
         'quotations' => array(
            'has-many' => array('\Models\Quotation','products','quotations_products')
        ),
    )
}

````
The results are successfully saved:
Table: quotations_products
id    products    quotations
1    1                5

But now I would like to add the quantity of the product to this table
id    products    quotations    qty
1    1                5                   5

How can I achieve this?
I have to run a query, or create a quotations_products model(not sure it will work) or is there a simple way?
Thanks

**Comment by ikkez** [comment] 2016-03-05 11:01
It's more or less a duplicate of https://github.com/ikkez/f3-cortex/issues/15
the recommendation is to create a new model on that table

**Closed** 2016-04-08 08:23 UTC
Labels: duplicate
