### ISSUE TITLE
Strange Problem with n to m relations

### ISSUE THREAD

**Issue by adkurz** [ikkez/f3-cortex#103] opened 2020-07-02 10:00 UTC
I'm porting my small note taker to f3 with cortex (master).
But with the has-many-relation in note and tag, there is a strange error.
array_key_exists() expects parameter 2 to be array, null given
[D:/xampp/htdocs/akn2/lib/ikkez/f3-cortex/lib/db/cortex.php:555] array_key_exists()

The fieldconf of the models is:
note:

  protected $fieldConf = [
    'name' => [
      'type' => 'varchar(' . self::NAME_MAX_LENGTH . ')',
      'passThrough' => true,
      'nullable' => false
    ],
    'user_id'  => [
      'belongs-to-one' => '\Model\User',
      'nullable' => false
    ],
    'note' => [
      'type' => \DB\SQL\Schema::DT_TEXT,
      'nullable' => false
    ],
    'created' => [
      'type' => \DB\SQL\Schema::DT_TIMESTAMP,
      'nullable' => false
    ],
    'last_modified' => [
      'type' => \DB\SQL\Schema::DT_TIMESTAMP,
      'nullable' => false
    ],
    'tags' => [
      'has-many' => ['\Model\Tag', 'note_id', 'tag2note']
    ]
  ];

tag:
  protected $fieldConf = [
    'name' => [
      'type' => 'varchar(' . self::NAME_MAX_LENGTH . ')',
      'passThrough' => true,
      'nullable' => false
    ],
    'notes' => [
      'has-many' => ['\Model\Note', 'tag_id', 'tag2note']
    ],
    'user_id' => [
      'belongs-to-one' => '\Model\User',
      'nullable' => false
    ]
  ];
Have I make a mistake or is this a problem with Cortex?
php: 7.3
F3: latest release
Cortex: Master

**Comment by ikkez** [comment] 2020-07-02 10:13
Hi there. Are `note_id` and `tag_id` the column names in the pivot table tag2note?
$Actually I think there's no option for custom fields names yet. It should rather be the field name used in the foreign model's $fieldConf .. so `tags` and `notes`. The pivot column names are then auto-generated. This is probably a duplicate of #54 ... I'll try to fix that one ;)

**Comment by ikkez** [comment] 2020-07-05 23:02
I've added the feature in the latest commit. When you checkout dev-master, you should now be able to set your custom keys.

note:
```
'tags' => [
  'has-many' => ['\Model\Tag', 'note_id', 'tag2note',
  'relField' => 'note_id']
]
```

tag:
```
'notes' => [
  'has-many' => ['\Model\Note', 'tags', 'tag2note',
  'relField' => 'tag_id']
]
```

**Closed** 2020-07-07 14:33 UTC
Labels: duplicate, feature ★
