### ISSUE TITLE
Cannot redeclare class DB\SQL\Schema error

### ISSUE THREAD

**Issue by GhaziTriki** [ikkez/f3-cortex#25] opened 2016-04-23 21:45 UTC
Hello,

I wasn't sure about where to put this issue in the "schema-builder" projet or here.

I have this issue when I have ```$fieldConf``` property for my User model class. If I remove it the error is gone.

```php
class User
{
    protected $table = 'users';

    protected $fieldConf = [
        'settings' => [
            'has-many' => ['\models\UserSetting', 'user_id']
        ]
    ];
}

class UserSetting
{
    protected $table = 'users_settings';

    protected $fieldConf = [
        'user' => [
            'belongs-to-one' => '\models\User'
        ]
    ];
}
```

I have the following call stack trace

```
Fatal error: Cannot redeclare class DB\SQL\Schema in /var/www/html/vendor/ikkez/f3-schema-builder/lib/db/sql/schema.php on line 30

Call Stack:
    0.0001     237864   1. {main}() /var/www/html/public/index.php:0
    0.0071    1308536   2. application\Bootstrap->__construct() /var/www/html/public/index.php:27
    0.0347    2181728   3. Base->run() /var/www/html/app/classes/application/Bootstrap.php:75
    0.0355    2224312   4. Base->call() /var/www/html/vendor/bcosca/fatfree-core/base.php:1509
    0.0390    2275296   5. call_user_func_array:{/var/www/html/vendor/bcosca/fatfree-core/base.php:1683}() /var/www/html/vendor/bcosca/fatfree-core/base.php:1683
    0.0390    2275776   6. actions\users\Index->execute() /var/www/html/vendor/bcosca/fatfree-core/base.php:1683
    0.0402    2458304   7. models\User->__construct() /var/www/html/app/classes/actions/users/Index.php:26
    0.0402    2458640   8. models\Base->__construct() /var/www/html/app/classes/models/User.php:41
    0.0402    2458944   9. DB\Cortex->__construct() /var/www/html/app/classes/models/Base.php:78
    0.0402    2459712  10. DB\Cortex->initMapper() /var/www/html/vendor/ikkez/f3-cortex/lib/db/cortex.php:124
    0.0415    2475984  11. DB\Cortex::resolveRelationConf() /var/www/html/vendor/ikkez/f3-cortex/lib/db/cortex.php:156
    0.0415    2476744  12. spl_autoload_call() /var/www/html/vendor/ikkez/f3-cortex/lib/db/cortex.php:512
    0.0415    2476776  13. Composer\Autoload\ClassLoader->loadClass() /var/www/html/vendor/ikkez/f3-cortex/lib/db/cortex.php:512
    0.0415    2476776  14. Composer\Autoload\includeFile() /var/www/html/vendor/composer/ClassLoader.php:301
    0.0424    2613440  15. include('/var/www/html/vendor/ikkez/f3-schema-builder/lib/db/sql/schema.php') /var/www/html/vendor/composer/ClassLoader.php:412
```

**Comment by ikkez** [comment] 2016-04-23 23:11
Looks like a problem with your autoloader. What is this, what does it do and where comes this from?
```
0.0071`    1308536   2. application\Bootstrap->__construct() /var/www/html/public/index.php:27
0.0347    2181728   3. Base->run() /var/www/html/app/classes/application/Bootstrap.php:75
```
Is there another autoloader running?

**Comment by ikkez** [comment] 2016-04-23 23:15
Ahw wait I see there is composer autoloader doing things. I'm just wondering why it tries to include the schematic file twice. Have you configured your AUTOLOAD f3 var beside using composer?

**Comment by GhaziTriki** [comment] 2016-04-24 06:30
There is no "AUTOLOAD" in f3 configuration, I am only using composer. And the line 75 of the Boostrap just contains ```$f3->run()```

**Comment by GhaziTriki** [comment] 2016-04-24 06:52
This error happens only when ```$fieldConf``` is defined in loaded class that extends Cortex.

**Comment by ikkez** [comment] 2016-04-24 08:10
It has nothing to do with the `$fieldConf` var. Do you have the schema plugin twice in your project? The error says it cannot redeclare that class. to there must be the instance that the class was already included and somewhere it's included again.

**Comment by ikkez** [comment] 2016-04-24 08:13
You have setup a relation in your fieldConf property.. when the model is initialized first, it'll load the foreign model too, to read its fieldConf. At that position, the schema plugin, which is probably used in there, is initialized and so the autoloader things it has to load that class. which is obviously wrong.

**Comment by GhaziTriki** [comment] 2016-04-24 09:55
Autoloading is only done through composer, no additional autoloading is made.
At the top of ```resolveRelationConf``` I have added ```class_exists('\DB\SQL\Schema', false)``` and it says FALSE. When I add this class_exists('\DB\SQL\Schema') I get the same error.

**Comment by ikkez** [comment] 2016-04-24 18:39
sorry, I cannot reproduce your issue.. here is a working composer example... hope this helps you:
https://dl.dropboxusercontent.com/u/3077539/temp/cx-cmp.zip

**Comment by GhaziTriki** [comment] 2016-06-08 19:44
The example didn't work for me, I get the error below even after installing php5-sqlite package

```
Internal Server Error

could not find driver

[cortex/vendor/bcosca/fatfree-core/db/sql.php:466] PDO->__construct()
[cortex/index.php:15] DB\SQL->__construct()
```

**Comment by ikkez** [comment] 2016-06-09 09:28
That's just for the sake of that sample. you can of course use another configuration,i.e. a mysql database for testing.. just alter the index.php accordingly. the point it that composer is used for autoloading the composer packages, and the F3 autoloader cares about business code (`app/`). 
See https://github.com/F3Community/fatfree-composer-app
not sure what your composer config is, but following this sample, it all seem to work.

**Comment by ikkez** [comment] 2016-06-26 09:48
I'm closing this, as this is an autoloader / composer issue.

**Closed by ikkez** 2016-06-26 09:48 UTC

**Comment by adamlibusa** [comment] 2018-07-13 11:03
A hint: If you use `fatfree` with `composer`, try writing:
`$f3 = \Base::instance();`
instead of
`$f3 = require('vendor/bcosca/fatfree/lib/base.php');`
